/**
 * Dashboard Data Module
 *
 * Responsibilities:
 * - Provide fallback mock data when reports/dashboard_state.json is missing
 * - Attempt to load from reports/dashboard_state.json
 * - Avoid polluting the global scope more than necessary
 * - Be consumed by dashboard/dashboard.html + dashboard/dashboard.js
 */

window.DashboardData = (function () {
  const MOCK = {
    marketFocus: [
      { market: "Stocks (Equities)", symbol: "SPY", regime: "Sideways", reason: "High liquidity, mean-reversion setups favorable" },
      { market: "Futures", symbol: "MNQ", regime: "Trending", reason: "Nasdaq composite trending, breakout potential" },
      { market: "Crypto", symbol: "BTCUSDT", regime: "Volatile", reason: "Volatility expanding, swing strategies viable" },
      { market: "Options", symbol: "SPX", regime: "Sideways", reason: "Low IV rank, premium-selling strategies attractive" },
      { market: "Futures", symbol: "GC", regime: "Trending", reason: "Gold in defined uptrend" },
      { market: "Futures", symbol: "CL", regime: "Transition", reason: "Crude shifting; wait for directional clarity" }
    ],
    strategyQueue: [
      { id: "S-101", name: "MNQ VWAP Pullback", asset: "futures", status: "pending", type: "VWAP / breakout", timeframe: "5m" },
      { id: "S-102", name: "SPY Opening Range Breakout", asset: "stocks", status: "pending", type: "Breakout", timeframe: "15m" },
      { id: "S-103", name: "BTC RSI Divergence", asset: "crypto", status: "pending", type: "Mean Reversion", timeframe: "1h" },
      { id: "S-104", name: "SPX Iron Condor Income", asset: "options", status: "pending", type: "Options Income", timeframe: "Daily" },
      { id: "S-105", name: "GC Trend Continuation", asset: "futures", status: "pending", type: "Trend Following", timeframe: "4h" }
    ],
    approvedStrategies: [
      { id: "A-21", name: "ES Fair Value Gap Fill", asset: "futures", timeframe: "1h", pf: 1.85, sharpe: 1.42, mdd: 12.4, forwardSince: "2025-10-01" },
      { id: "A-22", name: "SPY Mean Reversion RSI", asset: "stocks", timeframe: "15m", pf: 1.62, sharpe: 1.18, mdd: 8.7, forwardSince: "2025-11-15" },
      { id: "A-23", name: "BTC Session Breakout", asset: "crypto", timeframe: "4h", pf: 1.97, sharpe: 1.55, mdd: 22.1, forwardSince: "2026-01-02" }
    ],
    rejectedStrategies: [
      { id: "R-09", name: "NQ Micro Scalper", asset: "futures", stage: "baseline", reason: "Profit factor 0.91; negative expectancy" },
      { id: "R-10", name: "AAPL Earnings Gap", asset: "stocks", stage: "risk_review", reason: "Excessive drawdown risk (41%)" },
      { id: "R-11", name: "XYZ Meme Coin Momentum", asset: "crypto", stage: "regime", reason: "Failed in sideways/transition regimes only" },
      { id: "R-12", name: "SPX Weekly Expiry Scalp", asset: "options", stage: "walk_forward", reason: "OOS performance drop 48%" }
    ],
    bestByAssetClass: {
      stocks: { id: "A-22", name: "SPY Mean Reversion RSI", pf: 1.62, sharpe: 1.18, mdd: 8.7 },
      futures: { id: "A-21", name: "ES Fair Value Gap Fill", pf: 1.85, sharpe: 1.42, mdd: 12.4 },
      options: { id: "A-24", name: "SPX Range Bound Condor", pf: 1.44, sharpe: 1.05, mdd: 6.3 },
      crypto: { id: "A-23", name: "BTC Session Breakout", pf: 1.97, sharpe: 1.55, mdd: 22.1 }
    },
    bestRiskAdjusted: {
      id: "A-21",
      name: "ES Fair Value Gap Fill",
      asset: "futures",
      timeframe: "1h",
      pf: 1.85,
      sharpe: 1.42,
      mdd: 12.4,
      why: "Stable parameter sensitivity and low turnover"
    },
    bestRegimeFiltered: {
      id: "A-25",
      name: "GC Trend Catching v2",
      asset: "futures",
      regime: "Bull regime only",
      pfWithoutFilter: 1.61,
      pfWithFilter: 2.12,
      note: "Filter applied: HMM bull regime + volume expansion"
    },
    forwardTestCandidates: [
      { id: "F-03", name: "NQ Opening Drive", approved: "2026-02-10", forwardStart: "2026-02-17", pf: 1.76, sharpe: 1.31 },
      { id: "F-04", name: "ETH Session Range Break", approved: "2026-02-08", forwardStart: "2026-02-15", pf: 1.54, sharpe: 1.09 }
    ],
    databaseStatus: {
      totalStrategies: 41,
      approved: 12,
      rejected: 18,
      forwardTesting: 4,
      queueSize: 7,
      databaseSize: "18.4 MB"
    },
    activityLog: [
      { time: "12:04", msg: "Strategy S-102 promoted to Quant Research" },
      { time: "11:58", msg: "Risk review completed for S-101: passed baseline" },
      { time: "11:42", msg: "Database schema updated: regime_analysis table migrated" },
      { time: "11:30", msg: "A-23 passed Monte Carlo survival gate (91%)" },
      { time: "11:15", msg: "New analysis generated by Market Selection Desk" },
      { time: "11:02", msg: "R-12 archived: poor walk-forward results" }
    ],
    firmHealth: {
      generated: 58,
      tested: 43,
      approved: 12,
      rejected: 18,
      forwardActive: 4,
      bestPF: 2.12,
      bestSharpe: 1.55,
      lowestDD: 6.3
    }
  };

  async function loadState() {
    try {
      const res = await fetch("reports/dashboard_state.json", { cache: "no-store" });
      if (!res.ok) throw new Error("dashboard_state.json not found");
      const json = await res.json();
      return { ...MOCK, ...json, loaded: true };
    } catch (err) {
      return { ...MOCK, loaded: false, loadError: err.message };
    }
  }

  async function getMarketFocus() {
    const state = await loadState();
    // The sync script currently only writes aggregate counts. If it later
    // writes richer state, this merges. Otherwise fallback to MOCK.
    const enriched = {
      marketFocus: state.marketFocus,
      firmHealth: {
        generated: state.generated,
        tested: state.tested,
        approved: state.approved,
        rejected: state.rejected,
        forwardActive: 0,
        bestPF: state.bestPF,
        bestSharpe: state.bestSharpe,
        lowestDD: state.lowestDD
      },
      databaseStatus: {
        totalStrategies: state.tested,
        approved: state.approved,
        rejected: state.rejected,
        forwardTesting: 0,
        queueSize: Math.max(0, (state.tested || 0) - (state.approved || 0) - (state.rejected || 0)),
        databaseSize: "auto"
      }
    };
    return enriched;
  }

  return { MOCK, loadState, getMarketFocus };
})();
