/**
 * Dashboard data layer + UI
 *
 * Live data source:  http://localhost:7433  (run `python api/run_api.py`)
 * Fallback:          MOCK object below, with optional reports/dashboard_state.json overlay
 */

// ---------------------------------------------------------------------------
// MOCK DATA — used when API server is offline
// ---------------------------------------------------------------------------

const MOCK = {
  marketFocus: [
    { market: "Stocks (Equities)", symbol: "SPY",     regime: "Sideways",   reason: "High liquidity, mean-reversion setups favorable" },
    { market: "Futures",           symbol: "MNQ",     regime: "Trending",   reason: "Nasdaq composite trending, breakout potential" },
    { market: "Crypto",            symbol: "BTCUSDT", regime: "Volatile",   reason: "Volatility expanding, swing strategies viable" },
    { market: "Options",           symbol: "SPX",     regime: "Sideways",   reason: "Low IV rank, premium-selling strategies attractive" },
    { market: "Futures",           symbol: "GC",      regime: "Trending",   reason: "Gold in defined uptrend" },
    { market: "Futures",           symbol: "CL",      regime: "Transition", reason: "Crude shifting; wait for directional clarity" }
  ],

  strategyQueue: [
    { id: "S-101", name: "MNQ VWAP Pullback",          asset: "futures", status: "pending", type: "VWAP / breakout",  timeframe: "5m" },
    { id: "S-102", name: "SPY Opening Range Breakout",  asset: "stocks",  status: "pending", type: "Breakout",         timeframe: "15m" },
    { id: "S-103", name: "BTC RSI Divergence",          asset: "crypto",  status: "pending", type: "Mean Reversion",   timeframe: "1h" },
    { id: "S-104", name: "SPX Iron Condor Income",      asset: "options", status: "pending", type: "Options Income",   timeframe: "Daily" },
    { id: "S-105", name: "GC Trend Continuation",       asset: "futures", status: "pending", type: "Trend Following",  timeframe: "4h" }
  ],

  approvedStrategies: [
    { id: "A-21", name: "ES Fair Value Gap Fill",    asset: "futures", timeframe: "1h",  pf: 1.85, sharpe: 1.42, mdd: 12.4, forwardSince: "2025-10-01" },
    { id: "A-22", name: "SPY Mean Reversion RSI",   asset: "stocks",  timeframe: "15m", pf: 1.62, sharpe: 1.18, mdd: 8.7,  forwardSince: "2025-11-15" },
    { id: "A-23", name: "BTC Session Breakout",      asset: "crypto",  timeframe: "4h",  pf: 1.97, sharpe: 1.55, mdd: 22.1, forwardSince: "2026-01-02" }
  ],

  rejectedStrategies: [
    { id: "R-09", name: "NQ Micro Scalper",           asset: "futures", stage: "baseline",     reason: "Profit factor 0.91; negative expectancy" },
    { id: "R-10", name: "AAPL Earnings Gap",          asset: "stocks",  stage: "risk_review",  reason: "Excessive drawdown risk (41%)" },
    { id: "R-11", name: "XYZ Meme Coin Momentum",    asset: "crypto",  stage: "regime",       reason: "Failed in sideways/transition regimes only" },
    { id: "R-12", name: "SPX Weekly Expiry Scalp",   asset: "options", stage: "walk_forward", reason: "OOS performance drop 48%" }
  ],

  bestByAssetClass: {
    stocks:  { id: "A-22", name: "SPY Mean Reversion RSI",  pf: 1.62, sharpe: 1.18, mdd: 8.7  },
    futures: { id: "A-21", name: "ES Fair Value Gap Fill",  pf: 1.85, sharpe: 1.42, mdd: 12.4 },
    options: { id: "A-24", name: "SPX Range Bound Condor",  pf: 1.44, sharpe: 1.05, mdd: 6.3  },
    crypto:  { id: "A-23", name: "BTC Session Breakout",    pf: 1.97, sharpe: 1.55, mdd: 22.1 }
  },

  bestRiskAdjusted: {
    id: "A-21", name: "ES Fair Value Gap Fill", asset: "futures", timeframe: "1h",
    pf: 1.85, sharpe: 1.42, mdd: 12.4, why: "Stable parameter sensitivity and low turnover"
  },

  bestRegimeFiltered: {
    id: "A-25", name: "GC Trend Catching v2", asset: "futures", regime: "Bull regime only",
    pfWithoutFilter: 1.61, pfWithFilter: 2.12,
    note: "Filter applied: HMM bull regime + volume expansion"
  },

  forwardTestCandidates: [
    { id: "F-03", name: "NQ Opening Drive",          approved: "2026-02-10", forwardStart: "2026-02-17", pf: 1.76, sharpe: 1.31 },
    { id: "F-04", name: "ETH Session Range Break",   approved: "2026-02-08", forwardStart: "2026-02-15", pf: 1.54, sharpe: 1.09 }
  ],

  databaseStatus: {
    totalStrategies: 41, approved: 12, rejected: 18,
    forwardTesting: 4, queueSize: 7, databaseSize: "18.4 MB"
  },

  activityLog: [
    { time: "12:04", msg: "Strategy S-102 promoted to Quant Research" },
    { time: "11:58", msg: "Risk review completed for S-101: passed baseline" },
    { time: "11:42", msg: "Database schema updated: regime_analysis table migrated" },
    { time: "11:30", msg: "A-23 passed Monte Carlo survival gate (91%)" },
    { time: "11:15", msg: "New analysis generated by Market Selection Desk" },
    { time: "11:02", msg: "R-12 archived: poor walk-forward results" }
  ],

  firmHealth: {
    generated: 58, tested: 43, approved: 12, rejected: 18,
    forwardActive: 4, bestPF: 2.12, bestSharpe: 1.55, lowestDD: 6.3
  }
};

// ---------------------------------------------------------------------------
// MOCK API ADAPTER
// ---------------------------------------------------------------------------

const api = {
  current: {
    marketFocus:           () => Promise.resolve(MOCK.marketFocus),
    strategyQueue:         () => Promise.resolve(MOCK.strategyQueue),
    approvedStrategies:    () => Promise.resolve(MOCK.approvedStrategies),
    rejectedStrategies:    () => Promise.resolve(MOCK.rejectedStrategies),
    bestByAssetClass:      () => Promise.resolve(MOCK.bestByAssetClass),
    bestRiskAdjusted:      () => Promise.resolve(MOCK.bestRiskAdjusted),
    bestRegimeFiltered:    () => Promise.resolve(MOCK.bestRegimeFiltered),
    forwardTestCandidates: () => Promise.resolve(MOCK.forwardTestCandidates),
    databaseStatus:        () => Promise.resolve(MOCK.databaseStatus),
    activityLog:           () => Promise.resolve(MOCK.activityLog),
    firmHealth:            () => Promise.resolve(MOCK.firmHealth)
  }
};

// ---------------------------------------------------------------------------
// LIVE API CONNECTION
// ---------------------------------------------------------------------------

const API_BASE = "http://localhost:7433";
const API_TIMEOUT_MS = 3000;

async function apiFetch(path) {
  try {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), API_TIMEOUT_MS);
    const res = await fetch(API_BASE + path, { signal: ctrl.signal, cache: "no-store" });
    clearTimeout(timer);
    if (!res.ok) return null;
    return await res.json();
  } catch (_e) {
    return null;
  }
}

// ---------------------------------------------------------------------------
// DATA NORMALIZERS — bridge API format ↔ mock format
// ---------------------------------------------------------------------------

function normalizeQueueItem(item) {
  return {
    id:            item.spec_id       || item.id,
    name:          item.name,
    asset:         item.asset_class   || item.asset,
    status:        item.stage         || item.status,
    type:          item.type          || item.timeframe,
    timeframe:     item.timeframe,
    profit_factor: item.profit_factor,
    days_in_stage: item.days_in_stage,
    symbol:        item.symbol,
  };
}

function normalizeActivity(item) {
  if (item.created_at) {
    let time = "--:--";
    try { time = new Date(item.created_at).toTimeString().slice(0, 5); } catch (_e) {}
    return { time, msg: item.message || "" };
  }
  return { time: item.time || "--:--", msg: item.msg || "" };
}

function pipelineToHealth(pipeline) {
  const t = pipeline.totals || {};
  return {
    generated:    t.ideas    || 0,
    tested:       t.specs    || 0,
    approved:     t.approved || 0,
    rejected:     t.rejected || 0,
    forwardActive: 0,
    bestPF:       null,
    bestSharpe:   null,
    lowestDD:     null,
  };
}

function mockDbToPipeline(db) {
  return {
    totals: {
      ideas:     db.totalStrategies || 0,
      specs:     db.totalStrategies || 0,
      backtests: 0,
      scored:    0,
      approved:  db.approved  || 0,
      rejected:  db.rejected  || 0,
    },
    spec_stage_counts: {},
    today: { backtests: 0, regime_analyses: 0 },
  };
}

// ---------------------------------------------------------------------------
// UTILITIES
// ---------------------------------------------------------------------------

async function loadStateIfAvailable() {
  try {
    const res = await fetch("reports/dashboard_state.json", { cache: "no-store" });
    if (!res.ok) return null;
    return await res.json();
  } catch (_e) {
    return null;
  }
}

function mergeState(state) {
  if (!state) return;
  api.current.firmHealth = () => Promise.resolve({
    generated:    state.generated,
    tested:       state.tested,
    approved:     state.approved,
    rejected:     state.rejected,
    forwardActive: 0,
    bestPF:       state.bestPF,
    bestSharpe:   state.bestSharpe,
    lowestDD:     state.lowestDD
  });
  api.current.databaseStatus = () => Promise.resolve({
    totalStrategies: state.tested,
    approved:        state.approved,
    rejected:        state.rejected,
    forwardTesting:  0,
    queueSize: Math.max(0, (state.tested || 0) - (state.approved || 0) - (state.rejected || 0)),
    databaseSize: "auto"
  });
}

function el(id) { return document.getElementById(id); }

function formatPct(v) {
  if (v === null || v === undefined) return "—";
  return `${v}%`;
}

function fmtNum(v) {
  if (v === null || v === undefined) return "—";
  return Number(v).toFixed(2);
}

function fmtPct(v) {
  if (v === null || v === undefined) return "—";
  return Number(v).toFixed(1) + "%";
}

function fmtComma(v) {
  if (v === null || v === undefined) return "—";
  return Number(v).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function ddStatusClass(used, limit) {
  if (!limit) return "";
  const pct = used / limit;
  if (pct >= 0.8) return "text-danger";
  if (pct >= 0.5) return "text-warn";
  return "text-success";
}

function ddFillClass(used, limit) {
  if (!limit) return "dd-fill-safe";
  const pct = used / limit;
  if (pct >= 0.8) return "dd-fill-danger";
  if (pct >= 0.5) return "dd-fill-warning";
  return "dd-fill-safe";
}

function ddStatusLabel(used, limit) {
  if (!limit) return "—";
  const pct = used / limit;
  if (pct >= 0.8) return "DANGER — DD limit nearly reached";
  if (pct >= 0.5) return "WARNING — DD usage elevated";
  return "SAFE";
}

function clampBar(value) {
  const n = Number(value);
  if (Number.isNaN(n)) return 50;
  return Math.min(100, Math.max(4, Math.round(n * 10)));
}

function assetClassIcon(asset) {
  const map = { stocks: "S", futures: "F", options: "O", crypto: "C" };
  return map[(asset || "").toLowerCase()] || "?";
}

function escapeHtml(str) {
  if (str === null || str === undefined) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function stageColorClass(stage) {
  const map = {
    draft:           "",
    coding:          "text-warn",
    spec_created:    "text-warn",
    pending:         "text-warn",
    backtesting:     "text-accent",
    forward_testing: "text-accent",
    regime_analyzed: "text-success",
    optimized:       "text-success",
    approved:        "text-success",
    rejected:        "text-danger",
  };
  return map[stage] || "";
}

function stagePillClass(stage) {
  const map = {
    approved:        "pill-success",
    rejected:        "pill-danger",
    backtesting:     "pill-accent",
    forward_testing: "pill-accent",
    regime_analyzed: "pill-warn",
    optimized:       "pill-warn",
  };
  return map[stage] || "";
}

function gradeClass(grade) {
  if (!grade) return "";
  if (grade === "A+" || grade === "A") return "text-success";
  if (grade === "B")                    return "text-warn";
  if (grade === "C")                    return "text-accent";
  return "text-danger";
}

function regimeClass(regime) {
  const map = {
    Trending:               "text-success",
    Volatile:               "text-warn",
    Sideways:               "text-accent",
    "Sideways/Range-bound": "text-accent",
    "Mean-reverting":       "text-accent",
    Transition:             "text-danger",
    Bull:                   "text-success",
    Bear:                   "text-danger"
  };
  const key = (regime || "").toLowerCase();
  for (const k of Object.keys(map)) {
    if (key.includes(k.toLowerCase())) return map[k];
  }
  return "";
}

// ---------------------------------------------------------------------------
// RENDER FUNCTIONS
// ---------------------------------------------------------------------------

function renderMarketFocus(items) {
  const root = el("marketFocus");
  if (!items || !items.length) {
    root.innerHTML = "<div class='muted'>No markets selected</div>";
    return;
  }
  root.innerHTML = items.map(m => `
    <div class="list-item">
      <div class="item-icon">${assetClassIcon(m.asset || m.market)}</div>
      <div>
        <div class="item-title">${escapeHtml(m.market)}</div>
        <div class="muted">${escapeHtml(m.symbol)} · ${escapeHtml(m.reason || "")}</div>
      </div>
      <div class="item-value ${regimeClass(m.regime)}">${escapeHtml(m.regime)}</div>
    </div>
  `).join("");
}

function renderQueue(items) {
  const root = el("strategyQueue");
  el("queueCount").textContent = items ? items.length : 0;
  root.innerHTML = (items || []).map(raw => {
    const s = normalizeQueueItem(raw);
    const stale = (s.days_in_stage || 0) > 7;
    return `
      <div class="list-item">
        <div class="item-icon">${assetClassIcon(s.asset)}</div>
        <div>
          <div class="item-title">${escapeHtml(s.name)}</div>
          <div class="muted">${escapeHtml(s.symbol || s.type || "")} · ${escapeHtml(s.timeframe || "")}</div>
        </div>
        <div class="item-value muted">${escapeHtml(String(s.id || ""))}</div>
        <div class="item-value ${stageColorClass(s.status)}">${escapeHtml(s.status || "pending")}${stale ? " ⚠" : ""}</div>
      </div>
    `;
  }).join("");
}

function renderFirmHealth(h) {
  const root = el("firmHealth");
  if (!h) { root.innerHTML = "<div class='muted'>No data</div>"; return; }
  const rows = [
    { label: "Generated",   value: h.generated },
    { label: "Tested",      value: h.tested },
    { label: "Approved",    value: h.approved },
    { label: "Rejected",    value: h.rejected },
    { label: "Fwd Active",  value: h.forwardActive },
    { label: "Best PF",     value: h.bestPF },
    { label: "Best Sharpe", value: h.bestSharpe },
    { label: "Lowest DD",   value: formatPct(h.lowestDD) }
  ];
  root.innerHTML = rows.map(r => `
    <div class="meter">
      <div class="label">${r.label}</div>
      <div class="bar"><div class="fill" style="width:${clampBar(r.value)}%"></div></div>
      <div class="value">${r.value ?? "—"}</div>
    </div>
  `).join("");
}

function renderApproved(items) {
  const root = el("approvedStrategies");
  root.innerHTML = (items || []).map(s => `
    <div class="list-item">
      <div class="item-icon">${assetClassIcon(s.asset)}</div>
      <div>
        <div class="item-title">${escapeHtml(s.name)}</div>
        <div class="muted">${escapeHtml(s.timeframe || "")} · PF ${fmtNum(s.pf)}</div>
      </div>
      <div class="item-value">Sharpe ${fmtNum(s.sharpe)}</div>
      <div class="item-value text-success">${fmtPct(s.mdd)} DD</div>
    </div>
  `).join("");
}

function renderRejected(items) {
  const root = el("rejectedStrategies");
  root.innerHTML = (items || []).map(s => `
    <div class="list-item">
      <div class="item-icon">?</div>
      <div>
        <div class="item-title">${escapeHtml(s.name)}</div>
        <div class="muted">${escapeHtml(s.reason || "")}</div>
      </div>
      <div class="item-value muted">${escapeHtml(s.stage || "")}</div>
      <div class="item-value text-danger">Rejected</div>
    </div>
  `).join("");
}

function renderBestByAssetClass(obj) {
  const root = el("bestByAssetClass");
  const rows = [
    { label: "Stocks",  v: obj.stocks  },
    { label: "Futures", v: obj.futures },
    { label: "Options", v: obj.options },
    { label: "Crypto",  v: obj.crypto  }
  ];
  root.innerHTML = rows.map(r => `
    <div class="list-item">
      <div class="item-icon">${assetClassIcon(r.label.toLowerCase())}</div>
      <div>
        <div class="item-title">${r.v ? escapeHtml(r.v.name) : "—"}</div>
        <div class="muted">${r.v ? `${escapeHtml(r.label)} · PF ${fmtNum(r.v.pf)}` : ""}</div>
      </div>
      <div class="item-value muted">${r.v ? r.v.id : "—"}</div>
      <div class="item-value ${r.v && r.v.pf >= 1.5 ? "text-success" : "text-warn"}">${r.v ? fmtPct(r.v.mdd) : "—"}</div>
    </div>
  `).join("");
}

function renderBestRiskAdjusted(obj) {
  const root = el("bestRiskAdjusted");
  if (!obj) { root.innerHTML = "<div class='muted'>No candidate yet</div>"; return; }
  root.innerHTML = `
    <div class="detail-widget">
      <div class="row">
        <div><strong>${escapeHtml(obj.name)}</strong> <span class="badge">${escapeHtml(obj.asset)}</span></div>
        <div class="muted">PF ${fmtNum(obj.pf)} · Sharpe ${fmtNum(obj.sharpe)} · MDD ${fmtPct(obj.mdd)}</div>
        <div>${escapeHtml(obj.timeframe || "")}</div>
        <div class="muted">${escapeHtml(obj.why || "")}</div>
      </div>
    </div>
  `;
}

function renderBestRegimeFiltered(obj) {
  const root = el("bestRegimeFiltered");
  if (!obj) { root.innerHTML = "<div class='muted'>No candidate yet</div>"; return; }
  root.innerHTML = `
    <div class="row">
      <div>
        <div><strong>${escapeHtml(obj.name)}</strong> <span class="badge text-accent">${escapeHtml(obj.regime)}</span></div>
        <div class="muted">Without filter PF ${fmtNum(obj.pfWithoutFilter)} → With filter PF ${fmtNum(obj.pfWithFilter)}</div>
        <div class="muted">${escapeHtml(obj.note || "")}</div>
      </div>
    </div>
  `;
}

function renderForwardTests(items) {
  const root = el("forwardTestCandidates");
  root.innerHTML = (items || []).map(s => `
    <div class="list-item">
      <div class="item-icon">F</div>
      <div>
        <div class="item-title">${escapeHtml(s.name)}</div>
        <div class="muted">Since ${escapeHtml(s.forwardStart || s.approved || "")}</div>
      </div>
      <div class="item-value">PF ${fmtNum(s.pf)}</div>
      <div class="item-value text-accent">${escapeHtml(s.id)}</div>
    </div>
  `).join("");
}

function renderPipelineStatus(data) {
  const root = el("pipelineStatus");
  if (!root) return;
  if (!data) {
    root.innerHTML = "<div class='muted'>API offline — run <code>python api/run_api.py</code></div>";
    return;
  }
  const t = data.totals || {};
  const stages = data.spec_stage_counts || {};
  const stageEntries = Object.entries(stages);
  const today = data.today || {};
  root.innerHTML = `
    <div class="row">
      <div class="status-block"><div class="title">Ideas</div><div class="value">${t.ideas || 0}</div></div>
      <div class="status-block"><div class="title">Specs</div><div class="value">${t.specs || 0}</div></div>
      <div class="status-block"><div class="title">Backtests</div><div class="value">${t.backtests || 0}</div></div>
      <div class="status-block"><div class="title">Scored</div><div class="value">${t.scored || 0}</div></div>
      <div class="status-block"><div class="title">Approved</div><div class="value text-success">${t.approved || 0}</div></div>
      <div class="status-block"><div class="title">Rejected</div><div class="value text-danger">${t.rejected || 0}</div></div>
    </div>
    ${stageEntries.length ? `<div class="stage-pills">${stageEntries.map(([s, n]) => `<span class="pill ${stagePillClass(s)}">${escapeHtml(s)}: ${n}</span>`).join("")}</div>` : ""}
    <div class="muted" style="margin-top:6px;font-size:0.8em;">Today — backtests: ${today.backtests || 0} · regime analyses: ${today.regime_analyses || 0}</div>
  `;
}

function renderRankings(data) {
  const root = el("researchRankings");
  const countEl = el("rankingsCount");
  if (!root) return;
  if (countEl) countEl.textContent = data ? (data.count || 0) : 0;
  if (!data || !data.items || !data.items.length) {
    root.innerHTML = "<div class='muted'>No scored strategies yet. Run <code>score_strategy()</code> to populate.</div>";
    return;
  }
  root.innerHTML = data.items.map(s => `
    <div class="list-item">
      <div class="item-icon">${assetClassIcon(s.asset_class)}</div>
      <div>
        <div class="item-title">${escapeHtml(s.name)}</div>
        <div class="muted">${escapeHtml(s.symbol || "")} · ${escapeHtml(s.timeframe || "")}</div>
      </div>
      <div class="item-value">${s.profit_factor ? `PF ${fmtNum(s.profit_factor)}` : "—"}</div>
      <div class="item-value ${gradeClass(s.grade)}">${escapeHtml(s.grade || "—")} · ${fmtNum(s.composite_score)}</div>
    </div>
  `).join("");
}

function renderPropFirm(data) {
  const profileEl = el("propFirmProfile");
  const root = el("propFirmCandidates");
  if (!root) return;

  if (profileEl && data && data.profile) {
    const p = data.profile;
    const ddPct     = ((p.trailing_drawdown_limit || 0) * 100).toFixed(0);
    const dailyPct  = ((p.daily_loss_limit        || 0) * 100).toFixed(0);
    const targetPct = ((p.profit_target           || 0) * 100).toFixed(0);
    profileEl.innerHTML = `
      <div class="prop-firm-header">
        <strong>${escapeHtml(p.firm_name)} ${escapeHtml(p.account_label)}</strong>
        <span class="muted">DD ${ddPct}% · Daily ${dailyPct}% · Target ${targetPct}%</span>
      </div>
    `;
  } else if (profileEl) {
    profileEl.innerHTML = "";
  }

  if (!data || !data.items || !data.items.length) {
    root.innerHTML = "<div class='muted'>No approved strategies yet.</div>";
    return;
  }
  root.innerHTML = data.items.map(s => `
    <div class="list-item">
      <div class="item-icon">${assetClassIcon(s.asset_class)}</div>
      <div>
        <div class="item-title">${escapeHtml(s.name)}</div>
        <div class="muted">${escapeHtml(s.symbol || "")} · ${escapeHtml(s.timeframe || "")}</div>
      </div>
      <div class="item-value">${s.profit_factor ? `PF ${fmtNum(s.profit_factor)}` : "—"}</div>
      <div class="item-value ${s.eligible === true ? "text-success" : s.eligible === false ? "text-danger" : ""}">
        ${s.eligible === true ? "Eligible" : s.eligible === false ? "Review" : "—"}
      </div>
    </div>
  `).join("");
}

function renderActivityLog(items) {
  const root = el("activityLog");
  root.innerHTML = (items || []).map(i => `
    <div class="log-entry"><strong>${escapeHtml(i.time)}</strong> ${escapeHtml(i.msg)}</div>
  `).join("");
}

function renderNT8Account(data) {
  const root = el("nt8Account");
  if (!root) return;
  const snap = data && data.snapshot;
  if (!snap) {
    root.innerHTML = "<div class='muted'>No NT8 account data — run <code>python connectors/ninjatrader/nt8_sync.py</code></div>";
    return;
  }
  const ddUsed  = snap.trailing_drawdown_used  || 0;
  const ddLimit = snap.trailing_drawdown_limit  || 1;
  const ddPct   = Math.min(100, (ddUsed / ddLimit) * 100);
  const pnlClass = (snap.daily_pnl || 0) >= 0 ? "text-success" : "text-danger";
  root.innerHTML = `
    <div class="row">
      <div class="status-block">
        <div class="title">Account</div>
        <div class="value">${escapeHtml(snap.account_id || "—")}</div>
      </div>
      <div class="status-block">
        <div class="title">Equity</div>
        <div class="value">$${fmtComma(snap.equity)}</div>
      </div>
      <div class="status-block">
        <div class="title">Daily PnL</div>
        <div class="value ${pnlClass}">${(snap.daily_pnl || 0) >= 0 ? "+" : ""}$${fmtComma(snap.daily_pnl || 0)}</div>
      </div>
      <div class="status-block">
        <div class="title">Strategy</div>
        <div class="value">${escapeHtml(snap.active_strategy_id || "—")}</div>
      </div>
    </div>
    <div class="dd-section">
      <div class="dd-label">
        <span class="muted">Trailing Drawdown</span>
        <span class="${ddStatusClass(ddUsed, ddLimit)}">$${fmtComma(ddUsed)} / $${fmtComma(ddLimit)}</span>
      </div>
      <div class="dd-bar">
        <div class="dd-fill ${ddFillClass(ddUsed, ddLimit)}" style="width:${ddPct.toFixed(1)}%"></div>
      </div>
      <div class="dd-status ${ddStatusClass(ddUsed, ddLimit)}">${ddStatusLabel(ddUsed, ddLimit)}</div>
    </div>
    <div class="muted" style="font-size:0.8em;margin-top:6px;">Snapshot: ${escapeHtml(snap.snapshot_at || "—")}</div>
  `;
}

function renderNT8Trades(data) {
  const root    = el("nt8Trades");
  const summary = el("nt8TradeSummary");
  const countEl = el("nt8TradeCount");
  if (!root) return;

  const items    = (data && data.items) || [];
  if (countEl) countEl.textContent = items.length;

  const totalPnl = items.reduce((sum, t) => sum + (t.pnl || 0), 0);
  const wins     = items.filter(t => (t.pnl || 0) > 0).length;
  const losses   = items.filter(t => (t.pnl || 0) <= 0).length;
  const pnlTotalClass = totalPnl >= 0 ? "text-success" : "text-danger";

  if (summary) {
    summary.innerHTML = `
      <div class="nt8-summary">
        <span class="summary-item"><span class="muted">Trades</span> ${items.length}</span>
        <span class="summary-item"><span class="muted">Total PnL</span> <span class="${pnlTotalClass}">${totalPnl >= 0 ? "+" : ""}$${fmtComma(totalPnl)}</span></span>
        <span class="summary-item"><span class="muted">W/L</span> <span class="text-success">${wins}W</span> / <span class="text-danger">${losses}L</span></span>
      </div>
    `;
  }

  if (!items.length) {
    root.innerHTML = "<div class='muted'>No NT8 trades imported — run <code>python connectors/ninjatrader/nt8_sync.py</code></div>";
    return;
  }

  root.innerHTML = items.map(t => {
    const pnlClass = (t.pnl || 0) > 0 ? "text-success" : "text-danger";
    const dirClass = t.direction === "LONG" ? "text-success" : "text-danger";
    const entryDate = (t.entry_time || "").slice(0, 10);
    const entryTime = (t.entry_time || "").slice(11, 16);
    const exitTime  = (t.exit_time  || "").slice(11, 16);
    return `
      <div class="list-item">
        <div class="item-icon">F</div>
        <div>
          <div class="item-title">${escapeHtml(t.symbol || "—")} <span class="${dirClass}">${escapeHtml(t.direction || "")}</span></div>
          <div class="muted">${entryDate} ${entryTime}→${exitTime} · ${escapeHtml(t.strategy_id || t.account_id || "")}</div>
        </div>
        <div class="item-value muted">×${t.quantity || 1}</div>
        <div class="item-value ${pnlClass}">${(t.pnl || 0) >= 0 ? "+" : ""}$${fmtComma(t.pnl || 0)}</div>
      </div>
    `;
  }).join("");
}

function renderAttribution(data) {
  const root    = el("strategyAttribution");
  const countEl = el("attributionCount");
  if (!root) return;
  const items = (data && data.items) || [];
  if (countEl) countEl.textContent = items.length;
  if (!items.length) {
    root.innerHTML = "<div class='muted'>No NT8 trades imported yet — run <code>python connectors/ninjatrader/nt8_sync.py</code></div>";
    return;
  }
  const maxAbsPnl = Math.max(...items.map(s => Math.abs(s.total_pnl || 0)), 1);
  root.innerHTML = items.map(s => {
    const pnl      = s.total_pnl || 0;
    const pnlClass = pnl >= 0 ? "text-success" : "text-danger";
    const barW     = Math.min(100, (Math.abs(pnl) / maxAbsPnl) * 100).toFixed(1);
    const barClass = pnl >= 0 ? "attr-bar-positive" : "attr-bar-negative";
    const wrClass  = (s.win_rate || 0) >= 50 ? "text-success" : "text-danger";
    const pfStr    = s.profit_factor != null ? fmtNum(s.profit_factor) : "—";
    const lastDate = (s.last_trade_time || "").slice(0, 16).replace("T", " ");
    return `
      <div class="attr-card">
        <div class="attr-header">
          <div>
            <span class="item-title">${escapeHtml(s.strategy_id || "—")}</span>
            ${s.asset_class ? `<span class="badge">${escapeHtml(s.asset_class)}</span>` : ""}
            ${s.symbol      ? `<span class="muted"> ${escapeHtml(s.symbol)}</span>` : ""}
            ${s.timeframe   ? `<span class="muted">· ${escapeHtml(s.timeframe)}</span>` : ""}
          </div>
          <div class="attr-pnl ${pnlClass}">${pnl >= 0 ? "+" : ""}$${fmtComma(pnl)}</div>
        </div>
        <div class="attr-bar-wrap">
          <div class="attr-bar ${barClass}" style="width:${barW}%"></div>
        </div>
        <div class="attr-stats">
          <span><span class="muted">Trades</span> ${s.trade_count || 0}</span>
          <span><span class="muted">W/L</span> <span class="text-success">${s.wins || 0}W</span> / <span class="text-danger">${s.losses || 0}L</span></span>
          <span class="${wrClass}"><span class="muted">Win Rate</span> ${s.win_rate || 0}%</span>
          <span><span class="muted">PF</span> ${pfStr}</span>
          <span><span class="muted">Avg W</span> <span class="text-success">$${fmtComma(s.avg_win)}</span></span>
          <span><span class="muted">Avg L</span> <span class="text-danger">$${fmtComma(s.avg_loss)}</span></span>
          <span><span class="muted">Best</span> <span class="text-success">$${fmtComma(s.best_trade)}</span></span>
          <span><span class="muted">Worst</span> <span class="text-danger">$${fmtComma(s.worst_trade)}</span></span>
          <span class="muted">Net (after comm): <span class="${(s.net_pnl || 0) >= 0 ? "text-success" : "text-danger"}">$${fmtComma(s.net_pnl)}</span></span>
        </div>
        ${lastDate ? `<div class="attr-last muted">Last trade: ${escapeHtml(lastDate)}</div>` : ""}
      </div>
    `;
  }).join("");
}

// ---------------------------------------------------------------------------
// REFRESH — tries live API first, falls back to mock
// ---------------------------------------------------------------------------

async function refresh() {
  try {
    const health = await apiFetch("/health");

    if (health && health.status === "ok") {
      const pill = el("apiStatus");
      if (pill) { pill.className = "status-pill online"; pill.textContent = "API Online"; }

      const [queue, rankings, pipeline, propFirm, activity, nt8Acct, nt8Trd, attr] = await Promise.all([
        apiFetch("/strategy-queue"),
        apiFetch("/research-rankings"),
        apiFetch("/pipeline-status"),
        apiFetch("/prop-firm-candidates"),
        apiFetch("/activity-feed"),
        apiFetch("/nt8-account"),
        apiFetch("/nt8-trades"),
        apiFetch("/strategy-attribution"),
      ]);

      if (queue)    renderQueue(queue.items || []);
      if (rankings) renderRankings(rankings);
      if (pipeline) { renderPipelineStatus(pipeline); renderFirmHealth(pipelineToHealth(pipeline)); }
      if (propFirm) renderPropFirm(propFirm);
      if (activity) renderActivityLog((activity.items || []).map(normalizeActivity));
      renderNT8Account(nt8Acct || { snapshot: null });
      renderNT8Trades(nt8Trd  || { count: 0, items: [] });
      renderAttribution(attr   || { count: 0, items: [] });

      // Panels without live endpoints yet → keep mock
      const [mf, app, rej, asset, risk, regime, fwd] = await Promise.all([
        api.current.marketFocus(),
        api.current.approvedStrategies(),
        api.current.rejectedStrategies(),
        api.current.bestByAssetClass(),
        api.current.bestRiskAdjusted(),
        api.current.bestRegimeFiltered(),
        api.current.forwardTestCandidates(),
      ]);
      renderMarketFocus(mf);
      renderApproved(app);
      renderRejected(rej);
      renderBestByAssetClass(asset);
      renderBestRiskAdjusted(risk);
      renderBestRegimeFiltered(regime);
      renderForwardTests(fwd);

      el("lastUpdated").textContent = health.timestamp || new Date().toISOString();
      logActivity(`API connected · ${health.strategy_specs || 0} specs · ${health.table_count || 0} tables`);
      return;
    }

    // API offline — fall back to mock / dashboard_state.json
    const pill = el("apiStatus");
    if (pill) { pill.className = "status-pill"; pill.textContent = "Mock Data"; }

    const state = await loadStateIfAvailable();
    if (state) mergeState(state);

    const [mf, q, app, rej, asset, risk, regime, fwd, db, log, hlth] = await Promise.all([
      api.current.marketFocus(),
      api.current.strategyQueue(),
      api.current.approvedStrategies(),
      api.current.rejectedStrategies(),
      api.current.bestByAssetClass(),
      api.current.bestRiskAdjusted(),
      api.current.bestRegimeFiltered(),
      api.current.forwardTestCandidates(),
      api.current.databaseStatus(),
      api.current.activityLog(),
      api.current.firmHealth()
    ]);

    renderMarketFocus(mf);
    renderQueue(q);
    renderApproved(app);
    renderRejected(rej);
    renderBestByAssetClass(asset);
    renderBestRiskAdjusted(risk);
    renderBestRegimeFiltered(regime);
    renderForwardTests(fwd);
    renderPipelineStatus(mockDbToPipeline(db));
    renderActivityLog(log);
    renderFirmHealth(hlth);
    renderRankings({ count: 0, items: [] });
    renderPropFirm({ profile: null, count: 0, items: [] });
    renderNT8Account({ snapshot: null });
    renderNT8Trades({ count: 0, items: [] });
    renderAttribution({ count: 0, items: [] });

    el("lastUpdated").textContent = new Date().toISOString();
    logActivity("API offline — using mock data");
  } catch (err) {
    console.error("Dashboard refresh failed:", err);
    logActivity("Refresh failed: " + err.message);
  }
}

function logActivity(message) {
  const root = el("activityLog");
  if (!root) return;
  const time = new Date().toTimeString().slice(0, 5);
  const entry = document.createElement("div");
  entry.className = "log-entry";
  entry.innerHTML = `<strong>${escapeHtml(time)}</strong> ${escapeHtml(message)}`;
  root.prepend(entry);
  while (root.children.length > 20) root.lastChild.remove();
}

/* UI wiring */
document.addEventListener("DOMContentLoaded", () => {
  el("refreshBtn").addEventListener("click", refresh);
  el("layoutToggle").addEventListener("click", () => {
    document.body.classList.toggle("compact");
  });
  refresh();
});
